//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaqAPI.Datos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class abpos
    {
        public int idAbordaje { get; set; }
        public System.DateTime fecha { get; set; }
        public string idSupervisor { get; set; }
        public string idObra { get; set; }
        public string idOperador { get; set; }
        public string riesgo { get; set; }
        public string desvio { get; set; }
        public Nullable<bool> casco { get; set; }
        public Nullable<bool> lentes { get; set; }
        public Nullable<bool> guantes { get; set; }
        public Nullable<bool> uniforme { get; set; }
        public Nullable<bool> zapatos { get; set; }
        public Nullable<bool> uni_fajado { get; set; }
        public Nullable<bool> tapones { get; set; }
        public Nullable<bool> mascarilla { get; set; }
        public Nullable<bool> careta { get; set; }
        public Nullable<bool> arnes { get; set; }
        public Nullable<bool> polainas { get; set; }
        public Nullable<bool> peto { get; set; }
        public Nullable<bool> gogles { get; set; }
        public Nullable<bool> otros { get; set; }
        public string otro_descrip { get; set; }
        public string act_inseguros { get; set; }
        public string acc_correctiva { get; set; }
        public string cond_inseguras { get; set; }
        public string compromisos { get; set; }
    
        public virtual obras obras { get; set; }
        public virtual operadores operadores { get; set; }
        public virtual operadores operadores1 { get; set; }
    }
}
