//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaqAPI.Datos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inspec
    {
        public int idInspeccion { get; set; }
        public int docInspeccion { get; set; }
        public System.DateTime fecha { get; set; }
        public string idSupervisor { get; set; }
        public string idEconomico { get; set; }
        public string idOperador { get; set; }
        public string turno { get; set; }
        public Nullable<int> horometro { get; set; }
        public string idResponsableMtto { get; set; }
        public string frenos { get; set; }
        public string frenos_obs { get; set; }
        public string alarma_rev { get; set; }
        public string alarma_rev_obs { get; set; }
        public string nivel_aceite { get; set; }
        public string nivel_aceite_obs { get; set; }
        public string motor { get; set; }
        public string motor_obs { get; set; }
        public string transmision { get; set; }
        public string transmision_obs { get; set; }
        public string fugas_aceite { get; set; }
        public string fugas_aceite_obs { get; set; }
        public string nivel_agua { get; set; }
        public string nivel_agua_obs { get; set; }
        public string extinguidor { get; set; }
        public string extinguidor_obs { get; set; }
        public string luces { get; set; }
        public string luces_obs { get; set; }
        public string torreta { get; set; }
        public string torreta_obs { get; set; }
        public string neumaticos { get; set; }
        public string neumaticos_obs { get; set; }
        public string pernos_bujes { get; set; }
        public string pernos_bujes_obs { get; set; }
        public string direccion { get; set; }
        public string direccion_obs { get; set; }
        public string espejos_retrovisores { get; set; }
        public string espejos_retrovisores_obs { get; set; }
        public string claxon { get; set; }
        public string claxon_obs { get; set; }
        public string cinturon_seguridad { get; set; }
        public string cinturon_seguridad_obs { get; set; }
    
        public virtual maquinaria maquinaria { get; set; }
        public virtual operadores operadores { get; set; }
        public virtual operadores operadores1 { get; set; }
        public virtual operadores operadores2 { get; set; }
    }
}
