//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaqAPI.Datos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ubicacion
    {
        public int idUbicacion { get; set; }
        public string idEconomico { get; set; }
        public string idOperador { get; set; }
        public string idObra { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public string comentarios { get; set; }
        public string idUsuario { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public decimal hodometro { get; set; }
        public Nullable<int> odometro { get; set; }
        public string sello { get; set; }
        public Nullable<int> litros { get; set; }
        public Nullable<int> horometro { get; set; }
        public string ventana { get; set; }
    
        public virtual maquinaria maquinaria { get; set; }
        public virtual obra obras { get; set; }
        public virtual operadore operadores { get; set; }
        public virtual operadore operadores1 { get; set; }
    }
}
