//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaqAPI.Datos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ubicacion
    {
        public int idUbicacion { get; set; }
        public string idEconomico { get; set; }
        public string idOperador { get; set; }
        public string idObra { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public string comentarios { get; set; }
        public string idUsuario { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public decimal hodometro { get; set; }
        public Nullable<int> odometro { get; set; }
        public string sello { get; set; }
        public Nullable<int> litros { get; set; }
        public Nullable<int> horometro { get; set; }
        public string ventana { get; set; }
    
        public virtual maquinaria maquinaria { get; set; }
        public virtual obras obras { get; set; }
        public virtual operadores operadores { get; set; }
        public virtual operadores operadores1 { get; set; }
    }
}
