//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaqAPI.Datos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public string idUsuario { get; set; }
        public string Nombre { get; set; }
        public string passw { get; set; }
        public string estatus { get; set; }
        public string TipoEmpleado { get; set; }
        public System.DateTime fecha_alta { get; set; }
    }
}
