//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaqAPI.Datos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public string idUsuario { get; set; }
        public string Nombre { get; set; }
        public string passw { get; set; }
        public string estatus { get; set; }
        public string TipoEmpleado { get; set; }
        public System.DateTime fecha_alta { get; set; }
    }
}
